srmsystem/accounts/urls.py
from django.urls import path
from .views import (RegisterView,
                    SignInView,
                    SignUpView,
                    MainPageView,)


app_name: str = 'accounts'
urlpatterns: list = [
    path("", RegisterView.as_view(), name="register"),
    path("login/", SignInView.as_view(), name='login'),
    path("logout/", SignUpView.as_view(), name='logout'),
    path("main/", MainPageView.as_view(), name='main-page'),
]

srmsystem/ads/urls.py
from django.urls import path
from .views import (AdsListView,
                    AdsCreateView,
                    AdsDeleteView,
                    AdsDetailView,
                    AdsUpdateView,
                    AdsStatisticView,)


app_name: str = 'ads'
urlpatterns: list = [
    path('ads/', AdsListView.as_view(), name='ads'),
    path('ads/new/', AdsCreateView.as_view(), name='ads-create'),
    path('ads/<int:pk>/delete/', AdsDeleteView.as_view(), name='ads-delete'),
    path('ads/<int:pk>/', AdsDetailView.as_view(), name='ads-detail'),
    path('ads/<int:pk>/edit/', AdsUpdateView.as_view(), name='ads-update'),
    path('ads/statistic/', AdsStatisticView.as_view(), name='ads-statistic'),
]

srmsystem/srmsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns: list = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('services.urls')),
    path('', include('ads.urls')),
    path('', include('leads.urls')),
    path('', include('contracts.urls')),
    path('', include('customers.urls')),
    path('', include('statistic.urls')),
]

srmsystem/accounts/models.py
from django.db import models

srmsystem/ads/models.py
from django.db import models
from services.models import Service


class PromotionChannel(models.Model):
    """Модель канала продвижения"""

    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name


class Ads(models.Model):
    """Модель рекламной компании"""

    name = models.CharField(max_length=50, blank=True)
    product = models.ForeignKey(Service, on_delete=models.CASCADE)
    promotion_channel = models.ForeignKey(PromotionChannel, on_delete=models.CASCADE, blank=True, null=True)
    budget = models.DecimalField(default=0, max_digits=9, decimal_places=2)
    leads_count = models.IntegerField(blank=True, null=True)
    customers_count = models.IntegerField(blank=True, null=True)
    profit = models.FloatField(blank=True, null=True, default=0)

    def __str__(self):
        return self.name

srmsystem/contracts/models.py
from django.db import models
from services.models import Service
from customers.models import Customers


def file_contracts_directory_path(instance: "Contracts", filename: str) -> str:
    return f"files/file_contracts_{instance.customer}/{filename}"


class Contracts(models.Model):
    """Модель контракта"""

    customer = models.ForeignKey(Customers, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True)
    product = models.ForeignKey(Service, on_delete=models.CASCADE, blank=True)
    file = models.FileField(blank=True, null=True, upload_to=file_contracts_directory_path)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    cost = models.DecimalField(default=0, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.name

srmsystem/leads/models.py
from django.db import models
from ads.models import Ads


class Leads(models.Model):
    """Модель потенциального клиента"""

    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    phone = models.IntegerField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    ads = models.ForeignKey(Ads, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

srmsystem/services/models.py
from django.db import models


class Service(models.Model):
    """Модель услуги"""

    name = models.CharField(max_length=30, blank=True, unique=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    price = models.DecimalField(default=0, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.name

srmsystem/accounts/views.py
from typing import Any
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpRequest
from django.views.generic import View, CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy


class RegisterView(CreateView):
    """Cтраница регистрации пользователей"""

    form_class = UserCreationForm
    template_name: str = 'accounts/register_form.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form) -> HttpResponseRedirect:
        response: HttpResponseRedirect = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


class SignInView(LoginView):
    """Вход пользователей, имеющих назначенную администратором роль"""

    template_name: str = 'accounts/login_form.html'
    success_url = reverse_lazy('accounts:main-page')


class SignUpView(LogoutView):
    """Выход с сайта"""

    next_page = reverse_lazy("accounts:register")


class MainPageView(View):
    """Главная страница сайта"""

    def get(self, request: Any) -> HttpRequest:
        return render(request, 'accounts/main-page.html')

srmsystem/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>CRM</title>
</head>
<body>

<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="/">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if perms.services.view_service %}
            <li><a href="/products/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Услуги</span>
            </a></li>
            {% endif %}
            {% if perms.ads.view_ads %}
            <li><a href="/ads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.leads.view_leads %}
            <li><a href="/leads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Лиды</span>
            </a></li>
            {% endif %}
            {% if perms.contracts.view_contracts %}
            <li><a href="/contracts/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.customers.view_customers %}
            <li><a href="/customers/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <a href="/statistic/" class="bar-item text-decoration-none px-3 py-3 d-block">
                    <span class="px-1">Общая статистика</span>
                </a>
            </li>
            <li>
                <hr>
            </li>
            <li>
                <br>
            </li>
            <li>
                <span class="px-1">Пользователь: {{ request.user.first_name }} {{ request.user.last_name }}</span>
            </li>
            <li>
                <span class="px-1">Роль: {{ request.user.groups.first }}</span>
            </li>
            <li>
                <br>
            </li>
            <li>
                <a class="bar-item text-decoration-none px-3 py-3 d-block">
                    <form method="POST" action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                        <button><i class="fas fa-sign-out-alt"></i><span class="px-1">Выход</span></button>
                    </form>
                </a>
            </li>
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

srmsystem/accounts/templates/accounts/login_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card px-5 py-5" id="form1">
                <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit">Войти</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

srmsystem/accounts/templates/accounts/main-page.html
{% extends 'accounts/base.html' %}

srmsystem/accounts/templates/accounts/register_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card px-5 py-5" id="form1">
                <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit">Зарегистрироваться</button>
                </form>
                <br>
                <div>
                    <a href="{% url 'accounts:login' %}">Уже есть аккаунт? Войти</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>