srmsystem/ads/urls.py
from django.urls import path
from .views import (AdsListView,
                    AdsCreateView,
                    AdsDeleteView,
                    AdsDetailView,
                    AdsUpdateView,
                    AdsStatisticView,)


app_name: str = 'ads'
urlpatterns: list = [
    path('ads/', AdsListView.as_view(), name='ads'),
    path('ads/new/', AdsCreateView.as_view(), name='ads-create'),
    path('ads/<int:pk>/delete/', AdsDeleteView.as_view(), name='ads-delete'),
    path('ads/<int:pk>/', AdsDetailView.as_view(), name='ads-detail'),
    path('ads/<int:pk>/edit/', AdsUpdateView.as_view(), name='ads-update'),
    path('ads/statistic/', AdsStatisticView.as_view(), name='ads-statistic'),
]

srmsystem/leads/urls.py
from django.urls import path
from .views import (LeadsListView,
                    LeadsCreateView,
                    LeadsDetailView,
                    LeadsUpdateView,
                    LeadsDeleteView,)


app_name: str = 'leads'
urlpatterns: list = [
    path('leads/', LeadsListView.as_view(), name='leads'),
    path('leads/new/', LeadsCreateView.as_view(), name='leads-create'),
    path('leads/<int:pk>/', LeadsDetailView.as_view(), name='leads-detail'),
    path('leads/<int:pk>/edit/', LeadsUpdateView.as_view(), name='leads-update'),
    path('leads/<int:pk>/delete/', LeadsDeleteView.as_view(), name='leads-delete'),
]

srmsystem/srmsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns: list = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('services.urls')),
    path('', include('ads.urls')),
    path('', include('leads.urls')),
    path('', include('contracts.urls')),
    path('', include('customers.urls')),
    path('', include('statistic.urls')),
]

srmsystem/customers/models.py
from django.db import models
from leads.models import Leads
# from contracts.models import Contracts
from ads.models import Ads


class Customers(models.Model):
    """Модель активного клиента"""

    lead = models.OneToOneField(Leads, on_delete=models.SET_NULL, blank=True, null=True)
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    phone = models.IntegerField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    ads = models.ForeignKey(Ads, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

srmsystem/leads/models.py
from django.db import models
from ads.models import Ads


class Leads(models.Model):
    """Модель потенциального клиента"""

    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    phone = models.IntegerField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    ads = models.ForeignKey(Ads, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

srmsystem/leads/forms.py
from django import forms
from .models import Leads


class LeadsForm(forms.ModelForm):
    """Форма создания/редактирования потенциального клиента"""

    class Meta:
        model = Leads
        fields: tuple = "first_name", "last_name", "phone", "email", "ads"
        labels: dict = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'phone': 'Телефон',
            'email': 'Емейл',
            'ads': 'Рекламная кампания'
        }

srmsystem/leads/views.py
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse
from .models import Leads
from .forms import LeadsForm


class LeadsListView(ListView):
    """Список потенцальных клиентов"""

    template_name = 'leads/leads-list.html'
    queryset = Leads.objects.all()
    context_object_name = 'leads'


class LeadsCreateView(CreateView):
    """Создание потенциального клиента"""

    model = Leads
    form_class = LeadsForm
    success_url = reverse_lazy('leads:leads')

    def form_valid(self, form) -> HttpResponseRedirect:
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class LeadsDetailView(DetailView):
    """Просмотр детальной страницы потенциального клиента"""

    template_name: str = "leads/leads-detail.html"
    queryset = Leads.objects.all()
    context_object_name: str = 'leads'


class LeadsUpdateView(UpdateView):
    """Редактирование потенциального клиента"""

    model = Leads
    form_class = LeadsForm
    template_name_suffix: str = '_update_form'

    def get_success_url(self) -> str:
        return reverse('leads:leads-detail',
                       kwargs={"pk": self.object.pk})


class LeadsDeleteView(DeleteView):
    """Удаление потенциального клиента"""

    model = Leads
    success_url = reverse_lazy('leads:leads')

srmsystem/leads/templates/leads/leads-detail.html
{% extends "accounts/base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация о лиде</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ object.last_name }} {{ object.first_name }}</h5>
                <p class="card-text">{{ object.phone }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ object.email }}</div>
                <div class="d-flex justify-content-center fw-bold justify-content-between">
                    <a href="/leads/{{ object.pk }}/edit" class="btn btn-primary">Редактировать</a>
                    <a href="/products/{{ product.pk }}/delete" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

srmsystem/leads/templates/leads/leads-list.html
{% extends "accounts/base.html" %}

{% block content %}
<h2 class="fw-bold">Лиды</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="/leads/new" class="btn btn-success p-2">Создать</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for lead in leads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="/leads/{{ lead.pk }}" class="text-decoration-none link-dark">{{ lead.last_name }} {{ lead.first_name }}</a>
                <a href="/leads/{{ lead.pk }}/delete" class="btn btn-danger">Удалить</a>
                {% if perms.customers.view_customers %}
                    <a href="/customers/new/{{ lead.pk }}" class="btn btn-primary p-2">Перевести в активного клиента</a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

srmsystem/leads/templates/leads/leads_confirm_delete.html
{% extends "accounts/base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ object.last_name }} {{ object.first_name }}"?</p>
        <form method="POST" action="/leads/{{ object.pk }}/delete/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

srmsystem/leads/templates/leads/leads_form.html
{% extends "accounts/base.html" %}

{% block content %}
<h2 class="fw-bold">Создание лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/leads/new/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

srmsystem/leads/templates/leads/leads_update_form.html
{% extends "accounts/base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/leads/{{ object.pk }}/edit/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}